### PR TITLE
Fix Documentation Site Build Errors

### LINKED ISSUE #281: Build Failure for the Documentation Site
**Describe the bug**

Building the documentation site fails with the following errors:

1. `Failing node: 
{
    id: "7108ea9e1e3ae720867cee37d299d752117e2624",
    ...
}`

2. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/components/Header.jsx`

3. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/components/seo.js`

4. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/components/sidebar/SidebarItems.jsx`

5. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/layouts/external-layout.js`

6. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/layouts/Layout.jsx`

7. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/src/layouts/module-components.js`

8. `There was a problem parsing the GraphQL query in file: /home/jenkins/workspace/ran-facing-services-tools_master/packages/documentation/node_modules/gatsby-transformer-sharp/src/fragments.js`

[Link](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fveteran-facing-services-tools/detail/master/232/pipeline) to failing Jenkins CI.

**To Reproduce**

`cd` into `packages/documentation`, and run: 
`GITHUB_API_KEY=your-personal-access-token yarn build`

**Expected behavior**

The build should successfully pass without any errors.

### PR DESCRIPTION
**Pull request by theodur**
## Description
This PR fixes the `build` errors for the documentation site and resolves #281.

The following changes were made to `packages/documentation`:
- Updated `@mdx-js`, `react-helmet`, `react-live`, Gatsby, and Gatsby related plugins
- Replaced the deprecated [`gatsby-mdx`](https://github.com/ChristopherBiscardi/gatsby-mdx) plugin with [`gatsby-plugin-mdx`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx).
- Replaced `./plugins/remark/gatsby-remark-mdx-mermaid` with [`gatsby-remark-mermaid`](https://github.com/remcohaszing/gatsby-remark-mermaid)
- Updated the `export` and `import` of `MegaMenu/arrow-right-blue.jsx `
- Modified the `graphql` query for the component list to sort the result in alphabetical order
- Updated the `MDXProvider` and `MDXRenderer` in `documentation/src/layouts/module-components.js`
- Updated the repo and file paths in `github-pages.json`
- Commented the `github-api-pages` local plugin in `gatsby-config.js` (This plugin hasn't been working for a while now as the pages in `github-pages.json` aren't found on the documentation site.)

## Testing done
Ran the documentation site locally and compared it with the live site.

## Acceptance criteria
- [ ] The documentation site builds successfully, and runs as expected.

## Definition of done
- [ ] Changes have been tested in vets-website
- [ ] Changes have been tested in IE11, if applicable
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

File: packages/documentation/gatsby-config.js [hunk 1]
```diff
@@ -38,8 +38,17 @@ module.exports = {
         start_url: `/`,
       },
     },
+    `gatsby-plugin-sass`,
```
Comment (billfienberg) [inline packages/documentation/gatsby-config.js:41]: Was the order of the plugins breaking anything?

File: packages/documentation/src/layouts/external-layout.js [hunk 2]
```diff
@@ -19,7 +18,7 @@ export default class ExternalLayout extends Component {
   }
 }
 
-export const pageQuery = graphql`
+export const pageQuery = `
```
Comment (billfienberg) [inline packages/documentation/src/layouts/external-layout.js:21]: Did you try adding the `graphql` function back after you got everything working? 

In one of my failed attempts to fix the build, I removed the `graphql` function, which made one error go away, but still didn't fix the build. 

I wonder if the build would still pass if you reverted the changes to this file. 🤷‍♂️

File: packages/documentation/src/layouts/module-components.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import React, { Component } from 'react';
 import { graphql } from 'gatsby';
-import MDXRenderer from 'gatsby-mdx/mdx-renderer';
-import { MDXProvider } from '@mdx-js/tag';
+import { MDXProvider } from '@mdx-js/react';
```
Comment (billfienberg) [inline packages/documentation/src/layouts/module-components.js:3]: These changes are necessary due to deprecations/version changes, correct?

File: packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx [hunk 4]
```diff
@@ -13,3 +13,5 @@ export const ArrowRightBlueSVG = () => (
     />
   </svg>
 );
+
+export default ArrowRightBlueSVG;
```
Comment (billfienberg) [inline packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx:17]: NIT: Was it necessary to change this from a named export to a default export?

File: packages/documentation/gatsby-config.js (hunk 1 above)
Comment (theodur) [reply packages/documentation/gatsby-config.js:41]: The order of the plugins shouldn't break things. I re ordered the `gatsby-plugin-mdx` because I was testing another plugin that had to be after the `gatsby-source-filesystem` and I never changed the order back. Most examples have the `gatsby-source-filesystem` before the mdx plugin but I don't think it's necessary. i can always revert the order to confirm too.

File: packages/documentation/src/layouts/module-components.js (hunk 3 above)
Comment (theodur) [reply packages/documentation/src/layouts/module-components.js:3]: That's correct, the `gatsby-mdx` plugin is deprecated, and the `@mdx-js/react` dependency is now used to render react.

File: packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx (hunk 4 above)
Comment (theodur) [reply packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx:17]: I was getting an error about this file specifically in one of my [commits](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fveteran-facing-services-tools/detail/try-bump-sharp/30/pipeline) after changing things:

```
error A page component must export a React component for it to be valid. Please make sure this file exports a React component:

/home/jenkins/workspace/ng-services-tools_try-bump-sharp/packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx
```

After updating the export the above error went away. Also default exports are used by the rest of the components so this helps with consistency.

File: packages/documentation/gatsby-config.js (hunk 1 above)
Comment (billfienberg) [reply packages/documentation/gatsby-config.js:41]: If the order doesn't matter, and the current order reflects the order of common examples, then I don't think it's necessary to revert the order.

File: packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx (hunk 4 above)
Comment (billfienberg) [reply packages/formation-react/src/components/MegaMenu/arrow-right-blue.jsx:17]: That makes sense. Thanks for the explanation.

File: packages/documentation/src/layouts/external-layout.js (hunk 2 above)
Comment (theodur) [reply packages/documentation/src/layouts/external-layout.js:21]: I was tried adding the `graphql` back locally and weirdly the build passes, but one of the steps fail:

```
ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fields" on type "MarkdownRemark".

If you don't expect "fields" to exist on the type "MarkdownRemark" it is most likely a typo.
However, if you expect "fields" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "fields" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "MarkdownRemark":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/layouts/external-layout.js:26:7

failed extract queries from components - 0.485s
```

With the `graphql` function removed, this step doesn't fail 👀.

Comment (billfienberg) [reply packages/documentation/src/layouts/external-layout.js:21]: 🤔
